name: Release

on:
  push:
    branches: release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
        scope: netatwork
    - run: npm ci
    - run: npm publish --access=public --@netatwork:registry=https://registry.npmjs.org/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
